[workspace]
resolver = "2"
members = [
  "blabber-core",
  "blabber-app/src-tauri",
  "blabber-root"]


[workspace.dependencies]
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
rand = "0.10.1"
zeroize = "1.9.0"
blake3 = "1.8.5"


anyhow = "1.0.103"
uuid = "1.23.5"


iroh = "1.0.2"
iroh-blobs = "0.103.0"
iroh-docs = "0.101.0"
iroh-gossip = "0.101.0"

postcard = { version = "1.1.3", features = ["alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
data-encoding = "2.11.0"
n0-future = "0.3.2"

base64 = "0.22"
mime_guess = "2"
toml = "0.8"

